# Generated by Django 2.2 on 2020-02-18 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tv_shows_app', '0005_auto_20200218_2240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tvshow',
            name='release_date',
            field=models.CharField(max_length=255),
        ),
    ]
